import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/app/_components/ui/sonner";
import Navbar from "@/app/_components/layout/navbar";
import AuthWrapper from "./_components/auth/auth-wrapper";
import { validateRequest } from "@/server/auth";
import { ThemeProvider } from "./_components/theme-provider";
import { TooltipProvider } from "./_components/plate-ui/tooltip";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await validateRequest();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Toaster
          richColors
          toastOptions={{
            classNames: {
              actionButton: "text-white bg-primary",
            },
          }}
        />
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthWrapper user={user}>
              <EdgeStoreProvider>
                <TooltipProvider>
                  <Navbar user={user} />

                  {children}
                </TooltipProvider>
              </EdgeStoreProvider>
            </AuthWrapper>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
